GIT_COMMANDS = {
    "git init": "Initialize a new Git repository locally",
    "git clone": "Clone an existing repository from a remote source like GitHub",
    "git status": "Show the current state of the working directory and staging area",
    "git add": "Add changes in files to the staging area",
    "git commit": "Record changes with a message",
    "git push": "Push local commits to a remote repository",
    "git pull": "Fetch and merge changes from a remote repository",
    "git fetch": "Fetch changes from a remote but do not merge",
    "git branch": "List, create, or delete branches",
    "git checkout": "Switch branches or restore working tree files",
    "git merge": "Join two or more development histories together",
    "git log": "Show the commit history",
    "git diff": "Show changes between commits, working directory, etc.",
    "git reset": "Reset current HEAD to the specified state",
    "git config": "Set Git configuration values like name and email",
    "git setup": "Apply a default Git config template for user setup",
    "git rebase": "Reapply commits on top of another base tip (advanced)",
    "git stash": "Temporarily save changes that are not ready to commit",
    "git tag": "Create, list, or delete tags",
}